import { SetMetadata } from "@nestjs/common";

export enum Permission {
  SCHOOL_CREATE,
  SCHOOL_READ,
  SCHOOL_UPDATE,
  SCHOOL_DELETE,
  FACULTY_CREATE,
  FACULTY_READ,
  FACULTY_UPDATE,
  FACULTY_DELETE,
  REP_REQ_READ,
  REP_REQ_UPDATE,
  REP_REQ_VERIFY,
  TEACHER_REQ_VERIFY,
  TEACHER_REQ_READ,
  TEACHER_REQ_UPDATE,
  CHANNEL_CREATE,
  CHANNEL_READ,
  CHANNEL_UPDATE,
  CHANNEL_DELETE,
  CHANNEL_MEMBER,
  POST_CREATE,
  POST_READ,
  POST_UPDATE,
  POST_DELETE,
  POST_VOTE,
  COMMENT_CREATE,
  COMMENT_READ,
  COMMENT_UPDATE,
  COMMENT_DELETE,
  COMMENT_VOTE,
  FEED_READ,
  USER_READ,
  USER_UPDATE,
  TEACHER_READ,
}

export const PERMISSIONS_KEY = "permissions";

export const RequirePermissions = (...permissions: Permission[]) => SetMetadata(PERMISSIONS_KEY, permissions);
