-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "authorUuid" DROP NOT NULL,
ALTER COLUMN "resVote" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "authorUuid" DROP NOT NULL,
ALTER COLUMN "resVote" SET DEFAULT 0;
